= VRC Bladder System
:icons: font
:toc:

== To Be Decided

* release animation max length
* audio queues

== TODOs

=== EZL

. Figure out what the clock logic with the motion time was again, because I set
it to the wrong param.  Fairly sure there was a blend tree here that got removed
"temporarily" that didn't get re-added.


== Timing

TODO

fill rate is 1ml per second, meaning a maximum of 600s (10 min) to fill.

== Development Notes (Draft)

=== Parameters

==== `bladder.fill.volume`

[cols=">1h,1m"]
|===
| Type             | float
| User Modifiable  | 游린 false
| Synchronized     | 游릴 true
| Expression Param | 游릴 true
|===

Bladder fill volume represented as a percentage of 600ml.

The player's selected bladder capacity will determine the maximum value that
this parameter can reach.  For example, given a max capacity of 5%, this
parameter will never go above `0.3`.

[IMPORTANT]
This value MUST not be directly modified by any means outside of the bladder
system's animation controller.


==== `bladder.emptying`

[cols=">1h,1m"]
|===
| Type             | bool
| User Modifiable  | 游릴 true
| Synchronized     | 游릴 true
| Expression Param | 游릴 true
|===

Flag indicating whether the player's 'bladder' is currently emptying.

A value of `true` indicates the bladder is emptying, while `false` indicates the
bladder is filling.

This parameter may be manually toggled to trigger a manual/intentional emptying
of the bladder.


==== `bladder.capacity`

[cols=">1h,1m"]
|===
| Type             | float
| User Modifiable  | 游릴 true
| Synchronized     | 游린 false
| Expression Param | 游릴 true
|===

The player's chosen bladder capacity.

A value of `0` disables the bladder system entirely.

Values greater than `0` set the bladder capacity to a percentage of a max
capacity of 600ml.

This value also directly controls the time, as the bladder fill rate is 1ml per
second.


==== `sys.bladder.state`

[cols=">1h,1m"]
|===
| Type             | int
| User Modifiable  | 游린 false
| Synchronized     | 游린 false
| Expression Param | 游린 false
|===

Internal system state enum.

[WARNING]
This value should not be exposed to the user, nor should it be visible in the
VRC expression parameters.

.Enum Values
* 0 = Disabled
* 1 = Filling
* 2 = Emptying Involuntarily
* 3 = Emptying Voluntarily


==== `sys.bladder.fill.percent`

[cols=">1h,1m"]
|===
| Type             | float
| User Modifiable  | 游린 false
| Synchronized     | 游린 false
| Expression Param | 游린 false
|===

Internal system tracker for the current bladder fill percentage when taking the
selected max capacity into account.

[WARNING]
This value should not be exposed to the user, nor should it be visible in the
VRC expression parameters.

=== Layers

==== `sys.bladder.ux`

User direct user interaction layer.

* Enables and disables the feature based on whether the user has selected a
  bladder capacity
* Handles notifications based on bladder fill %

===== Activate Bladder System

.Prerequisites
1. The player has configured a non-zero `bladder.capacity` parameter value.
2. The system state is currently disabled (`sys.bladder.state == 0`).

.Actions
* Sets the *local* parameter `sys.bladder.state` to `1`, indicating the system
is now in the "filling" state.
* Sets the *synced* parameter `bladder.fill.volume` to `0` to clear out any left
over value from previously enabling/disabling the feature.
* Plays the `sys.bladder.toast.enabled` animation to give user feedback that the
bladder system is working and enabled.


===== Deactivate Bladder System

.Prerequisites
1. The player has set the `bladder.capacity` setting back to zero.
2. The system is currently enabled (`sys.bladder.state > 0`).

.Actions
* Sets the *local* parameter `sys.bladder.state` to `0`, indicating the system
is now disabled.
* Plays the `sys.bladder.toast.disabled` animation to give user feedback that
the bladder system is now disabled.

[NOTE]
This action _DOES NOT_ change reset the `bladder.fill.volume` or
`bladder.emptying` parameters, allowing any current animation to complete.


===== Notification Triggers

.Prerequisites
1. The system is currently in the "filling" state (`sys.bladder.state == 1`).

.Actions
* Player notification animations fired at the following thresholds:
** 50%
** 75%
** 83%
** 90%
** 95%
** 100%


==== `sys.bladder.fill.clock`

Bladder fill level timing.  Fills the bladder volume by 0.4% every 2.4 seconds
until it reaches the selected capacity, or a maximum time of 600s (10 minutes).

The 0.4% and 2.4s values are based on 250 ticks spread over 600s.

0.4% => 0.004 => 1/250
2.4s => 600/250

===== Init

Default state exists only to loop back to <<Clock Tick>>

===== Clock Tick

.Prerequisites
1. System is in the "filling" state (`sys.bladder.state == 1`)
2. Bladder fill is less than 100% of the configured capacity.

.Timing
* Ticks every 2.4 seconds

.Actions
. Runs a single frame of the `sys.bladder.clock.percent` animation to update the
fill % value.

==== `sys.bladder.fill.triggers`

Handles the voluntary or involuntary bladder release events.

On release trigger, the fill volume will be reduced over time to 0 before the
counters reset and start again.
