= GottaGo System Configuration Parameters
:icons: font
:toc: left
:doc-url: https://puddlefluff.github.io/VRC-GottaGo-System
:sync-url: /sync-params.html

The following parameters are present in the avatar expression parameters files, however they are not intended to be
synchronzed.  These parameters are options modify the behavior of the system.

The expression menus included with the system have entries to set all of these options, but they may be modified by
other means instead of, or in addition to the included expression menus.


[WARNING]
By default, these parameters are not set to retain their names in the default VRCFury full controller.


== Bladder System

=== Enable System

[none]
* *Name*: `gg.bladder.opt.enabled`
* *Type*: `bool`
* *Menu*: Toggle

Controls whether the bladder system is enabled.  When disabled, all GG values will reset to their default state.


=== Manual Release

[none]
* *Name*: `gg.bladder.opt.release`
* *Type*: `bool`
* *Menu*: Button

When `true`, switches the system to 'release' mode, where the the bladder fill


=== Reset Release Totals

[none]
* *Name*: `gg.bladder.opt.release.total.reset`
* *Type*: `bool`
* *Menu*: Toggle

When `true`, tells the system to reset the release amount values back to `0`.

Once the release totals have been reset, this value will be automatically set back to `false`.


=== Max Hold Time

[none]
* *Name*: `gg.bladder.opt.time.max`
* *Type*: `float`
* *Menu*: Radial

Configures the maximum hold time from a minimum value of 30 seconds to a maximum value of 10 minutes.

The actual hold time may deviate from the configuration value by use of the optional avatar contacts which modify the
system speed.


=== Hold Time Radial Open

[none]
* *Name*: `gg.bladder.opt.radial.open`
* *Type*: `bool`
* *Menu*: Indirect

Indicates whether the player has the hold time option radial menu open.  When set to `true`, the bladder system idles,
awaiting the player's chosen hold time value.

[IMPORTANT]
This value should not be modified directly, it exists in the expression parameters by necessity.


== Bowels System
