= GottaGo Synchronizable Parameters
:icons: font

The following parameters are exposed by the GottaGo system for use in
avatar-specific animations or extensions. 

Any of the parameters listed that are not being used may safely be marked as
non-synchronized.

[WARNING]
These parameters are *READ ONLY*, the system does not read from these
parameters, and will overwrite values that are set from outside GottaGo.

[IMPORTANT]
The avatar expression parameters that are not included in this list are not
intended to be synchronized or used outside of the GottaGo system, however they
_may_ be modified by other means to change the system's behavior without use of
the included expression menu options.

== Bladder System

gg.bladder.volume::
+
--
Type: `float`

The current bladder fill volume as a percentage of 600ml (hold volume radial set
to 100%).
--

gg.bladder.pressure::
+
--
Type: `float`

The current bladder pressure as a percentage of chosen maximum volume.
--

gg.bladder.release.total::
+
--
Type: `float`

The total volume released as a percentage of 600ml (hold volume radial set to
100%).
--

gg.bladder.release.relative::
+
--
Type: `float`

The total volume released as a percentage of the chosen maximum volume.
--

gg.bladder.emptying::
+
--
Type: `bool`

Flag indicating whether the bladder volume is currently being released.
--


== Bowels System

gg.bowels.volume::
+
--
Type: `float`

The current bowels fill volume as a percentage of the maximum possible
configurable amount (hold volume radial set to 100%).
--

gg.bowels.pressure::
+
--
Type: `float`

The current bowel pressure as a percentage of chosen maximum.
--

gg.bowels.release.total::
+
--
Type: `float`

The total volume released as a percentage of the maximum possible configurable
amount (hold volume radial set to 100%).
--

gg.bowels.release.relative::
+
--
Type: `float`

The total volume released as a percentage of the chosen maximum volume.
--

gg.bowels.emptying::
+
--
Type: `bool`

Flag indicating whether the bladder volume is currently being released.
--
