= GottaGo Synchronizable Parameters
:icons: font
:toc: left

The following parameters are exposed by the GottaGo system for use in avatar-specific animations or extensions. 

Any parameters not being used to drive for your project's features may safely be marked as non-synchronized.


[WARNING]
These parameters are *READ ONLY*, the system does not read from these parameters, and will overwrite values that are set
from outside GottaGo.

[NOTE]
While expression parameters not included in this list are not intended to be used outside the GottaGo system, they may
be modified by other means to change the system's behavior without use of the included expression menu options.


== Bladder System

[#gg-bladder-volume]
=== `gg.bladder.volume

Type: `float`

The current bladder fill volume as a percentage of 600ml (hold volume radial at 100%).

[#gg-bladder-pressure]
=== `gg.bladder.pressure`

Type: `float`

The current bladder pressure as a percentage of chosen maximum volume.

[#gg-bladder-release-total]
=== `gg.bladder.release.total`

Type: `float`

The total volume released as a percentage of 600ml (hold volume radial at 100%).

[#gg-bladder-release-relative]
=== `gg.bladder.release.relative`

Type: `float`

The total volume released as a percentage of the chosen maximum volume.

[#gg-bladder-emptying]
=== `gg.bladder.emptying`

Type: `bool`

Flag indicating whether the bladder volume is currently being released.


== Bowels System

[#gg-bowels-volume]
=== `gg.bowels.volume`

Type: `float`

The current bowels fill volume as a percentage of the maximum possible amount (hold volume radial at 100%).

[#gg-bowels-pressure]
=== `gg.bowels.pressure`

Type: `float`

The current bowel pressure as a number that increases from `0.0` to `1.0` over the course of the chosen maximum hold
time.

[CAUTION]
The rate of pressure increase is not linear, as in it does not directly represent the current hold time.  The value

[#gg-bowels-release-total]
=== `gg.bowels.release.total`

Type: `float`

The total volume released as a percentage of the maximum possible amount (hold volume radial at 100%).

[#gg-bowels-release-relative]
=== `gg.bowels.release.relative`

Type: `float`

The total volume released as a percentage of the chosen maximum volume.

[#gg-bowels-emptying]
=== `gg.bowels.emptying`

Type: `bool`

Flag indicating whether the bladder volume is currently being released.
