= GottaGo System
:icons: font
:toc: left
:sectlinks:
:sectanchors:

== Parameters

=== Synchronizable Parameters

The following parameters are exposed by the GottaGo system for use in animations
and extensions. 

Any parameters not being used by your project's features may safely be marked as
non-synchronized.

[WARNING]
--
These parameters are *READ ONLY*, the system does not read from these
parameters, and will overwrite values that are set from outside GottaGo while
the system is active.

These parameters _may_ be written to and utilized while the system is disabled,
however, they will be reset once the system is activated.
--

[IMPORTANT]
While in pre-release development, the parameter names are likely to change!
If using the system, have a method of bulk renaming parameters _outside_ of
Unity available.


==== Bladder System

[TIP]
Bladder system parameters are prefixed with the text `g1.`

[#bladder-volume]
===== `g1.volume`

Type: `float`

The current bladder fill volume as a percentage of 600ml (hold volume radial at 100%).

[#bladder-pressure]
===== `g1.pressure`

Type: `float`

The current bladder pressure as a percentage of chosen maximum volume.

[#bladder-release-total]
===== `g1.release.total`

Type: `float`

The total volume released as a percentage of 600ml (hold volume radial at 100%).

[#bladder-release-relative]
===== `g1.release.relative`

Type: `float`

The total volume released as a percentage of the chosen maximum volume.


[CAUTION]
--
The rate of value increase is not linear, and has a curve as it approaches 100%.  This is due in part to the limited
ways in which math can be done without the ability to write custom scripts.

In future versions of the system, the increase will be updated to be a linear increase.
--

[#bladder-emptying]
===== `g1.emptying`

Type: `bool`

Flag indicating whether the bladder volume is currently being released.


==== Bowels System

[TIP]
Bowels system parameters are prefixed with the text `g2.`

[#bowels-volume]
===== `g2.volume`

Type: `float`

The current bowels fill volume as a percentage of the maximum possible amount (hold volume radial at 100%).

[#bowels-pressure]
===== `g2.pressure`

Type: `float`

The current bowel pressure as a number that increases from `0.0` to `1.0` over the course of the chosen maximum hold
time.


[#bowels-release-total]
===== `g2.release.total`

Type: `float`

The total volume released as a percentage of the maximum possible amount (hold volume radial at 100%).

[#bowels-release-relative]
===== `g2.release.relative`

Type: `float`

The total volume released as a percentage of the chosen maximum volume.


[CAUTION]
--
The rate of value increase is not linear, and has a curve as it approaches 100%.  This is due in part to the limited
ways in which math can be done without the ability to write custom scripts.

In future versions of the system, the increase will be updated to be a linear increase.
--

[#bowels-emptying]
===== `g2.emptying`

Type: `bool`

Flag indicating whether the bladder volume is currently being released.

=== Option Parameters


The following parameters are present in the avatar expression parameters files, however they are not intended to be
synchronzed.  These parameters are options modify the behavior of the system.

The expression menus included with the system have entries to set all of these options, but they may be modified by
other means instead of, or in addition to the included expression menus.


[WARNING]
By default, these parameters are not set to retain their names in the default VRCFury full controller.


==== Bladder System

===== Enable System

[none]
* *Name*: `gg.bladder.opt.enabled`
* *Type*: `bool`
* *Menu*: Toggle

Controls whether the bladder system is enabled.  When disabled, all GG values will reset to their default state.


===== Manual Release

[none]
* *Name*: `gg.bladder.opt.release`
* *Type*: `bool`
* *Menu*: Button

When `true`, switches the system to 'release' mode, where the the bladder fill


===== Reset Release Totals

[none]
* *Name*: `gg.bladder.opt.release.total.reset`
* *Type*: `bool`
* *Menu*: Toggle

When `true`, tells the system to reset the release amount values back to `0`.

Once the release totals have been reset, this value will be automatically set back to `false`.


===== Max Hold Time

[none]
* *Name*: `gg.bladder.opt.time.max`
* *Type*: `float`
* *Menu*: Radial

Configures the maximum hold time from a minimum value of 30 seconds to a maximum value of 10 minutes.

The actual hold time may deviate from the configuration value by use of the optional avatar contacts which modify the
system speed.


===== Hold Time Radial Open

[none]
* *Name*: `gg.bladder.opt.radial.open`
* *Type*: `bool`
* *Menu*: Indirect

Indicates whether the player has the hold time option radial menu open.  When set to `true`, the bladder system idles,
awaiting the player's chosen hold time value.

[IMPORTANT]
This value should not be modified directly, it exists in the expression parameters by necessity.


==== Bowels System
