name: Render Readme

on:
 push:
   branches:
   - main
   paths:
   - 'docs/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Clone Repo
      uses: actions/checkout@v4

    - uses: actions/upload-pages-artifact@v3
      with:
        path: docs/

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    steps:
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4